### ISSUE TITLE
Feature Request: Different Configs for Run vs Debug Profiles

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-extension-test-runner#33]
Often I want to debug tests but my mocha config has a particular timeout that causes them to fail. When clicking the debug test link in the test profile ui and starting the debug profile, I want to have a setting to specify a separate .vscode-test.mjs file so I can set the timeout higher (and maybe other settings) for those runs.

**Comment by connor4312** [comment]
I actually want to make a change to just disable the timeout during development. Would that work for you?

**Comment by JustinGrote** [comment]
That'd be totally fine too! I just figured there might be more use cases where people want to tweak their configs for other reasons, but timeout is my #1 reason right now.
