### ISSUE TITLE
Extension is causing unresponsive extension host

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-extension-test-runner#46]
I'm selfhosting on vscode-copilot, it looks like there's one function called `_syncFile` which is going crazy

![Image](https://github.com/user-attachments/assets/d61f17f9-92e8-40a5-b683-bc784f63cf3e)

```
Version: 1.93.0-insider
Commit: e1db90f81da28c0994b5d50dc2b51e964359e62d
Date: 2024-08-21T05:04:11.586Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

![Image](https://github.com/user-attachments/assets/cf2cd326-df66-48dc-b33d-8b94dc944175)

[extension-test-runner-CPU-20240822T065255.473Z.cpuprofile.txt.zip](https://github.com/user-attachments/files/16706612/extension-test-runner-CPU-20240822T065255.473Z.cpuprofile.txt.zip)

**Comment by connor4312** [comment]
This is not quite so bad for me, taking only 1.5s per sync, but we could fix it by debouncing it and/or moving it to a worker.
