### ISSUE TITLE
Is there a way to interact with the input box or quick pick(createInputBox) that runs during executionCommand?

### ISSUE THREAD

**Issue by pwsses** [microsoft/vscode-extension-test-runner#8]
Hello.
I develop Test code about command that run on the command palette.

my command has scenario which run some input box or quick pick in command. (I execute command using `vscode.commands.executeCommand`)
I want write string and pick item in my Test code.
But I don't know how. 
Do you have any way to use selenium or sinon, whatever.

Is there an official TC guide related to this?

Thank you.

**Comment by connor4312** [comment]
You might find https://github.com/redhat-developer/vscode-extension-tester which is a system for UI automation testing in VS Code. Alternatively you can manually use a library like Sinon to stub things out.
